server:
  port: 4000
  logger: true

db:
  type: 'postgres'
  port: 5555
  database: code_mentoring_learning
  username: codementoring
  password: codementoring

auth:
  jwtSecret: secret

jwt:
  expiresIn: 3600
