name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/'*'
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    # Run scripts separately for easier debugging.
    # - name: Install & build
    #   run: yarn install --frozen-lock-file
    - name: Lint
      run: yarn lint
    - name: Test and coverage
      run: yarn coverage
