name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/'*'
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    # Run scripts separately for easier debugging.
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Test and coverage
      run: yarn coverage

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      # Run scripts separately for easier debugging.
      - name: Install
        run: yarn install

      # NOTE: Workaround for https://github.community/t5/GitHub-Actions/How-to-push-to-protected-branches-in-a-GitHub-Action/td-p/29609
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Publish
        run: lerna publish -y --canary --preid ${GITHUB_REF##*/} --npm-tag=${GITHUB_REF##*/} --force-publish=*

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          owner: benjefferies
          repo: branch-protection-bot
