
name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/'*'
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    # - uses: codecov/codecov-action@v1
    #   with:
    #     # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    #     file: ./packages/api/coverage/lcov.info # optional
    #     flags: unittests # optional
    #     name: codecov-umbrella # optional
    #     fail_ci_if_error: true # optional (default = false)

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    # Run scripts separately for easier debugging.
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Upload coverage to Codecov
      run: yarn coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./packages/api/coverage/lcov.info
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: true
